CREATE DATABASE bd_controleleite;

USE bd_controleleite;

CREATE TABLE TURMA (
 TURMA VARCHAR(30) NOT NULL PRIMARY KEY,
 PADRINHO VARCHAR(50)
);

CREATE TABLE INVENTARIO (
 ID_ENTREGA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 QUANTIDADE INT,
 DATA_ENTREGA CHAR(10),
 TURMA VARCHAR(30)
);


ALTER TABLE INVENTARIO ADD CONSTRAINT FK_INVENTARIO_0 FOREIGN KEY (TURMA) REFERENCES TURMA (TURMA);


